site_name: Introducción a la inteligencia artificial
nav:
  - Introducción: ./index.md
  - Optimización: ./optimization.md
  - Algoritmos de optimización: ./gradient_descent.md
  - Regresiónn lineal: ./regression.md
  - Reducción de dimensionalidad: ./dimensionality_reduction.md
  - Redes neuronales lineales y  no lineales: ./linear_neural_network.md
  - Aprendizaje profundo: ./deep_learning.md
  - Mecanismo de atención: ./attention.md

#- katex optimization for large equations
extra_javascript:
  - javascripts/katex.js
  - javascripts/katex.min.js
  - javascripts/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - stylesheets/monokai.css
  - stylesheets/extra.css

theme:
  logo: assets/images/icon.png
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
  palette:
    primary: deep purple
    accent: deep purple
    scheme: slate
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
    #- navigation.tabs
    #- navigation.indexes
    #- toc.integrate

markdown_extensions:
  - codehilite
  - toc:
      toc_depth: 2
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight: # provide options that apply also to the superfences extension
      use_pygments: false

extra:
  generator: false
