site_name: Introducción a la inteligencia artificial
nav:
  - Introducción: ./index.md
  - Optimization: ./optimization.md
  - Gradient descent: ./gradient_descent.md
  - Regression: ./regression.md
  - Dimensionality reduction: ./dimensionality_reduction.md
  - Linear neural network: ./linear_neural_network.md
  - Perceptron: ./perceptron.md
  - Convolutional: ./convolutional.md
  - Recurrent: ./recurrent.md
  - CNN-RNN: ./cnnrnn.md
  - Attention: ./attention.md
  - Transformer: ./transformer.md
  - GAN's: ./gan.md
theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: custom
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.indexes
    #- toc.integrate
    - navigation.top

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

#- katex optimization for large equations
extra_javascript:
  - javascripts/katex.js
  - javascripts/katex.min.js
  - javascripts/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - stylesheets/extra.css
  #- stylesheets/dark_theme.css
  #- stylesheets/codehilite.css
extra:
  generator: false
